import {
  createCipheriv,
  createDecipheriv,
  randomBytes,
  timingSafeEqual,
} from "node:crypto";

/**
 * Authenticated encryption for the few secrets that have to live in the
 * database — currently mailbox passwords.
 *
 * AES-256-GCM, because the mailbox password is not only secret, it has to be
 * trustworthy: GCM's tag means a row someone tampered with fails to open
 * rather than decrypting to a different password. Plain AES-CBC would not
 * tell us.
 *
 * The key never appears in this repository. It is 32 random bytes, base64, in
 * MAIL_ENCRYPTION_KEY — generated by the owner and pasted into Railway:
 *
 *     node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"
 *
 * LOSING THE KEY MEANS LOSING THE PASSWORDS. That is the intended trade: a
 * stolen database dump is worthless on its own, and the recovery path for a
 * lost key is to re-enter the mailbox passwords, which takes a minute.
 * ROTATING the key means re-sealing every row; there is no silent fallback to
 * an old key, because a fallback is how a rotation quietly never finishes.
 *
 * Sealed form is `v1.<iv>.<tag>.<ciphertext>`, each part base64url. The
 * version prefix is there so a future scheme can be told apart from this one
 * rather than guessed at.
 */

const VERSION = "v1";
const KEY_BYTES = 32;
const IV_BYTES = 12; // 96 bits, the size GCM is defined for
const TAG_BYTES = 16;

export class SecretBoxError extends Error {}

function b64u(buffer: Buffer): string {
  return buffer.toString("base64url");
}

/**
 * Read per call rather than at module load: a test can set the variable, and
 * changing it in Railway takes effect on restart without a rebuild.
 */
function key(): Buffer {
  const raw = process.env.MAIL_ENCRYPTION_KEY;

  if (!raw) {
    throw new SecretBoxError(
      "MAIL_ENCRYPTION_KEY is not set, so mailbox passwords cannot be sealed or opened.",
    );
  }

  let decoded: Buffer;
  try {
    decoded = Buffer.from(raw, "base64");
  } catch {
    throw new SecretBoxError("MAIL_ENCRYPTION_KEY is not valid base64.");
  }

  if (decoded.length !== KEY_BYTES) {
    throw new SecretBoxError(
      `MAIL_ENCRYPTION_KEY must decode to ${KEY_BYTES} bytes; got ${decoded.length}.`,
    );
  }

  return decoded;
}

/** True when a key is configured and usable, without revealing anything about it. */
export function encryptionAvailable(): boolean {
  try {
    key();
    return true;
  } catch {
    return false;
  }
}

export function seal(plaintext: string): string {
  if (!plaintext) throw new SecretBoxError("Refusing to seal an empty secret.");

  const iv = randomBytes(IV_BYTES);
  const cipher = createCipheriv("aes-256-gcm", key(), iv);
  const body = Buffer.concat([
    cipher.update(plaintext, "utf8"),
    cipher.final(),
  ]);

  return [VERSION, b64u(iv), b64u(cipher.getAuthTag()), b64u(body)].join(".");
}

export function open(sealed: string): string {
  const parts = sealed.split(".");

  if (parts.length !== 4 || parts[0] !== VERSION) {
    throw new SecretBoxError("Sealed value is not in the expected format.");
  }

  const iv = Buffer.from(parts[1]!, "base64url");
  const tag = Buffer.from(parts[2]!, "base64url");
  const body = Buffer.from(parts[3]!, "base64url");

  if (iv.length !== IV_BYTES || tag.length !== TAG_BYTES) {
    throw new SecretBoxError("Sealed value has the wrong shape.");
  }

  const decipher = createDecipheriv("aes-256-gcm", key(), iv);
  decipher.setAuthTag(tag);

  try {
    return Buffer.concat([decipher.update(body), decipher.final()]).toString(
      "utf8",
    );
  } catch {
    // Either the key is wrong or the row was altered. Which one it is is not
    // the caller's business, and saying would help an attacker.
    throw new SecretBoxError(
      "Could not open the sealed value with the configured key.",
    );
  }
}

/** Constant-time compare, for the rare case two sealed secrets are checked. */
export function sameSecret(a: string, b: string): boolean {
  const left = Buffer.from(a, "utf8");
  const right = Buffer.from(b, "utf8");
  return left.length === right.length && timingSafeEqual(left, right);
}
